### ISSUE TITLE
t/09_filter.t fails

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/greple#11]
t/09_filter.t fails on my smokers, and looking at http://matrix.cpantesters.org/?dist=App-Greple%208.3306 , also on other people's smokers.

Excerpt of test log:
```
#   Failed test '--if'
#   at t/09_filter.t line 11.
#                   ''
#     doesn't match '(?^:\A\s*2\b)'
# Looks like you failed 1 test of 3.
t/09_filter.t ........... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

**Comment by kaz-utashiro** [comment]
Thank you.  This test works fine locally, and I don't know the reason why fails in test sites.  Enclosed in TODO block in 8.3401.

**Comment by eserte** [comment]
I did some experiments and found out that this test passes if I deactivate the "close STDIN" line like this:
```
diff --git i/t/Util.pm w/t/Util.pm
index 2c04507..53071df 100644
--- i/t/Util.pm
+++ w/t/Util.pm
@@ -41,7 +41,7 @@ package Greple {
        my $pid = (my $fh = new IO::File)->open('-|') // die "open: $@\n";
        if ($pid == 0) {
            open STDERR, ">&STDOUT";
-           close STDIN;
+#          close STDIN;
            greple(@{$obj->{OPTION}});
            exit 1;
        }
```
This is on a debian 8 system. However, I have to idea why the closing helps. Running the greple command manually looks fine to me, I see a "2" at the front and a colored "fox". The manual command:
```
/opt/perl-5.28.1/bin/perl "-I/home/e/eserte/.cpan/build/2019091921/App-Greple-8.3401-0/lib" "/home/e/eserte/.cpan/build/2019091921/App-Greple-8.3401-0/script/greple" "--if" "cat -n" "-e" "fox" "t/SAMPLE.txt" < /dev/null
```

**Comment by kaz-utashiro** [comment]
Interesting.  It is probably something related to the control terminal.  I don't remember why I closed STDIN, and it seems to be unnecessary.  Thank you!
