### ISSUE TITLE
tests failing on cygwin

### ISSUE THREAD

**Issue by stepht** [kaz-utashiro/greple#14]
t/00_load.t ............. 1/? # Testing App::Greple 8.5204, Perl 5.030003, /usr/bin/perl

...
t/10_select.t ........... ok
t/11_block.t ............ 6/?
#   Failed test '--block . (overflowed shorter block)'
#   at t/11_block.t line 28.
Wide character in print at /tmp/cpanm_t.d/p5lib/lib/perl5/Test2/Formatter/TAP.pm line 125.
#          got: 'いろ
# はに
# '
#     expected: '[いろ]
# [は]に
# '
# Looks like you failed 1 test of 7.
t/11_block.t ............ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests
t/12_error.t ............ 3/? utf8 "\xFE" does not map to Unicode at t/Runner.pm line 53.
t/12_error.t ............ 6/? utf8 "\xFE" does not map to Unicode at t/Runner.pm line 53.
utf8 "\xFE" does not map to Unicode at t/Runner.pm line 53.

Test Summary Report
-------------------
t/09_filter.t         (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1
t/11_block.t          (Wstat: 256 Tests: 7 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=19, Tests=112, 51 wallclock secs ( 0.11 usr  0.14 sys + 21.62 cusr 28.38 csys = 50.25 CPU)
Result: FAIL
FAIL
! Installing App::Greple failed. See /tmp/cpanm_t.d/work/1639245639.7801/build.log for details. Retry with --force to force install it.

these errors are new.
latest versions did not show this.
hth
--steph

**Comment by kaz-utashiro** [comment]
Thank you.  I figured out this happens when stdout is not a terminal.
Maybe I should change the behavior of --color option.
